samples({
  _16basb: { 'b1': 'ST-07/16basb.wav' },
  _16snared: { 'b1': 'ST-07/16snared.wav' },
  _16tom2: { 'b1': 'ST-07/16tom2.wav' },
  _4powerbrass: { 'b1': 'ST-07/4powerbrass.wav' },
  hit_me2: { 'b1': 'ST-07/HitMe2.wav' },
  adadadada: { 'b1': 'ST-07/adadadada.wav' },
  bass15: { 'b1': 'ST-07/bass15.wav' },
  bass50: { 'b1': 'ST-07/bass50.wav' },
  bass51: { 'b1': 'ST-07/bass51.wav' },
  bb1: { 'b1': 'ST-07/bb1.wav' },
  bc_pick: { 'b1': 'ST-07/bc-pick.wav' },
  bc_powerchord: { 'b1': 'ST-07/bc-powerchord.wav' },
  bdrum3: { 'b1': 'ST-07/bdrum3.wav' },
  bohemian: { 'b1': 'ST-07/bohemian.wav' },
  bomi: { 'b1': 'ST-07/bomi.wav' },
  brass: { 'b1': 'ST-07/brass.wav' },
  cc2: { 'b1': 'ST-07/cc2.wav' },
  cc3: { 'b1': 'ST-07/cc3.wav' },
  digdug2: { 'b1': 'ST-07/digdug2.wav' },
  doing: { 'b1': 'ST-07/doing.wav' },
  dumpfbass: { 'b1': 'ST-07/dumpfbass.wav' },
  durloop1: { 'b1': 'ST-07/durloop1.wav' },
  dxbass: { 'b1': 'ST-07/dxbass.wav' },
  echotrump: { 'b1': 'ST-07/echotrump.wav' },
  endblaster8: { 'b1': 'ST-07/endblaster8.wav' },
  georg_bass: { 'b1': 'ST-07/georg-bass.wav' },
  georg_bass2: { 'b1': 'ST-07/georg-bass2.wav' },
  georg_bdrum: { 'b1': 'ST-07/georg-bdrum.wav' },
  georg_carbreak: { 'b1': 'ST-07/georg-carbreak.wav' },
  georg_effekt: { 'b1': 'ST-07/georg-effekt.wav' },
  georg_guitar: { 'b1': 'ST-07/georg-guitar.wav' },
  georg_hihat: { 'b1': 'ST-07/georg-hihat.wav' },
  georg_sdrum: { 'b1': 'ST-07/georg-sdrum.wav' },
  georg_sdrum2: { 'b1': 'ST-07/georg-sdrum2.wav' },
  georg_voice: { 'b1': 'ST-07/georg-voice.wav' },
  georg_bdrum2: { 'b1': 'ST-07/georg.bdrum2.wav' },
  go2: { 'b1': 'ST-07/go2.wav' },
  hh_drum: { 'b1': 'ST-07/hh+drum.wav' },
  hh1: { 'b1': 'ST-07/hh1.wav' },
  hh2: { 'b1': 'ST-07/hh2.wav' },
  hhopen1: { 'b1': 'ST-07/hhopen1.wav' },
  highhat2: { 'b1': 'ST-07/highhat2.wav' },
  hubbardbas: { 'b1': 'ST-07/hubbardbas.wav' },
  hubbardping: { 'b1': 'ST-07/hubbardping.wav' },
  hubbardplick: { 'b1': 'ST-07/hubbardplick.wav' },
  hubbardsnare: { 'b1': 'ST-07/hubbardsnare.wav' },
  humancry: { 'b1': 'ST-07/humancry.wav' },
  iso_aahh: { 'b1': 'ST-07/iso aahh.wav' },
  iso_aahh2: { 'b1': 'ST-07/iso aahh2.wav' },
  iso_bdrum: { 'b1': 'ST-07/iso bdrum.wav' },
  iso_bdrum2: { 'b1': 'ST-07/iso bdrum2.wav' },
  iso_explod: { 'b1': 'ST-07/iso explod.wav' },
  iso_fff_platch: { 'b1': 'ST-07/iso fff.platch.wav' },
  iso_sdrum: { 'b1': 'ST-07/iso sdrum.wav' },
  iso_sdrum2: { 'b1': 'ST-07/iso sdrum2.wav' },
  iso_sdrum3: { 'b1': 'ST-07/iso sdrum3.wav' },
  iso_shot: { 'b1': 'ST-07/iso shot.wav' },
  iso_shot2: { 'b1': 'ST-07/iso shot2.wav' },
  iso_shut: { 'b1': 'ST-07/iso shut.wav' },
  iso_shut2: { 'b1': 'ST-07/iso shut2.wav' },
  iso_voice: { 'b1': 'ST-07/iso voice.wav' },
  iso_voice2: { 'b1': 'ST-07/iso voice2.wav' },
  iso_voice3: { 'b1': 'ST-07/iso voice3.wav' },
  klirr: { 'b1': 'ST-07/klirr .wav' },
  kraftsmatter: { 'b1': 'ST-07/kraftsmatter.wav' },
  laut_aehh: { 'b1': 'ST-07/laut aehh.wav' },
  lordbassdrum: { 'b1': 'ST-07/lordbassdrum.wav' },
  mollloop1: { 'b1': 'ST-07/mollloop1.wav' },
  plat4: { 'b1': 'ST-07/plat4.wav' },
  pop2: { 'b1': 'ST-07/pop2.wav' },
  roing: { 'b1': 'ST-07/roing.wav' },
  sb1: { 'b1': 'ST-07/sb1.wav' },
  scnep: { 'b1': 'ST-07/scnep.wav' },
  sdrum2: { 'b1': 'ST-07/sdrum2.wav' },
  skriik: { 'b1': 'ST-07/skriik.wav' },
  skrook: { 'b1': 'ST-07/skrook.wav' },
  snare17: { 'b1': 'ST-07/snare17.wav' },
  snare5: { 'b1': 'ST-07/snare5.wav' },
  snurre5: { 'b1': 'ST-07/snurre5.wav' },
  sp12bassdrum: { 'b1': 'ST-07/sp12bassdrum.wav' },
  sp12snare: { 'b1': 'ST-07/sp12snare.wav' },
  spanntrommel: { 'b1': 'ST-07/spanntrommel.wav' },
  stenin: { 'b1': 'ST-07/stenin.wav' },
  stenut: { 'b1': 'ST-07/stenut.wav' },
  ston: { 'b1': 'ST-07/ston.wav' },
  td1: { 'b1': 'ST-07/td1.wav' },
  tennis_aus: { 'b1': 'ST-07/tennis aus.wav' },
  tennis_boden: { 'b1': 'ST-07/tennis boden.wav' },
  tennis_cer: { 'b1': 'ST-07/tennis cer..wav' },
  tennis_close: { 'b1': 'ST-07/tennis close.wav' },
  tennis_klatschen: { 'b1': 'ST-07/tennis klatschen.wav' },
  tennis_netz: { 'b1': 'ST-07/tennis netz.wav' },
  tennis_open: { 'b1': 'ST-07/tennis open.wav' },
  tennis_quitsch: { 'b1': 'ST-07/tennis quitsch.wav' },
  tennis_time: { 'b1': 'ST-07/tennis time.wav' },
  tennissay0: { 'b1': 'ST-07/tennissay0.wav' },
  tennissay15: { 'b1': 'ST-07/tennissay15.wav' },
  tennissay30: { 'b1': 'ST-07/tennissay30.wav' },
  tennissay40: { 'b1': 'ST-07/tennissay40.wav' },
  thrustah: { 'b1': 'ST-07/thrustah.wav' },
  twee2: { 'b1': 'ST-07/twee2.wav' },
  v1: { 'b1': 'ST-07/v1.wav' },
  v2: { 'b1': 'ST-07/v2.wav' },
  v3: { 'b1': 'ST-07/v3.wav' },
  virus: { 'b1': 'ST-07/virus.wav' },
  virus2: { 'b1': 'ST-07/virus2.wav' },
  virus3: { 'b1': 'ST-07/virus3.wav' },
  voing: { 'b1': 'ST-07/voing.wav' }
}, 'github:fongelias/ias/main/converted')