samples({
  snare19: { 'b1': 'ST-08/SNARE19.wav' },
  animate_kick: { 'b1': 'ST-08/animate-kick.wav' },
  bass5: { 'b1': 'ST-08/bass5.wav' },
  eigeneexplosion: { 'b1': 'ST-08/eigeneexplosion.wav' },
  follow_me: { 'b1': 'ST-08/follow me.wav' },
  grosseexplosion: { 'b1': 'ST-08/grosseexplosion.wav' },
  insdiskii: { 'b1': 'ST-08/insdiskii.wav' },
  kleineexplosion: { 'b1': 'ST-08/kleineexplosion.wav' },
  ko_chor: { 'b1': 'ST-08/ko-chor.wav' },
  ko_chor2: { 'b1': 'ST-08/ko-chor2.wav' },
  ko_penalty: { 'b1': 'ST-08/ko-penalty.wav' },
  ko_pfiff: { 'b1': 'ST-08/ko-pfiff.wav' },
  ko_tor: { 'b1': 'ST-08/ko-tor.wav' },
  reinflugsound2: { 'b1': 'ST-08/reinflugsound2.wav' },
  schuss2: { 'b1': 'ST-08/schuss2.wav' },
  stabs: { 'b1': 'ST-08/stabs.wav' },
  start: { 'b1': 'ST-08/start.wav' },
  statsample1: { 'b1': 'ST-08/statsample1.wav' },
  statsample2: { 'b1': 'ST-08/statsample2.wav' },
  strings7k: { 'b1': 'ST-08/strings7k.wav' },
  welcome: { 'b1': 'ST-08/welcome....wav' },
  xout_voice3: { 'b1': 'ST-08/xout-voice3.wav' },
  xout_voice4: { 'b1': 'ST-08/xout-voice4.wav' },
  xout_weaponquit: { 'b1': 'ST-08/xout-weaponquit.wav' },
  yint_fauch: { 'b1': 'ST-08/yint fauch.wav' },
  yint_the_end: { 'b1': 'ST-08/yint the end.wav' },
  yint_voice: { 'b1': 'ST-08/yint voice.wav' },
  zent_argh: { 'b1': 'ST-08/zent argh.wav' },
  zent_argh2: { 'b1': 'ST-08/zent argh2.wav' },
  zent_argh3: { 'b1': 'ST-08/zent argh3.wav' },
  zent_au: { 'b1': 'ST-08/zent au!.wav' },
  zent_bass: { 'b1': 'ST-08/zent bass.wav' },
  zent_bdrum: { 'b1': 'ST-08/zent bdrum.wav' },
  zent_dogg: { 'b1': 'ST-08/zent dogg.wav' },
  zent_door: { 'b1': 'ST-08/zent door.wav' },
  zent_geraeusch: { 'b1': 'ST-08/zent geraeusch.wav' },
  zent_gittertor: { 'b1': 'ST-08/zent gittertor.wav' },
  zent_guitare1_2: { 'b1': 'ST-08/zent guitare1\'2.wav' },
  zent_guitare1: { 'b1': 'ST-08/zent guitare1.wav' },
  zent_guitare2: { 'b1': 'ST-08/zent guitare2.wav' },
  zent_guitare3: { 'b1': 'ST-08/zent guitare3.wav' },
  zent_guitare4: { 'b1': 'ST-08/zent guitare4.wav' },
  zent_hahaha: { 'b1': 'ST-08/zent hahaha.wav' },
  zent_hahahaha: { 'b1': 'ST-08/zent hahahaha.wav' },
  zent_hahahaha2: { 'b1': 'ST-08/zent hahahaha2.wav' },
  zent_hihat: { 'b1': 'ST-08/zent hihat.wav' },
  zent_hit: { 'b1': 'ST-08/zent hit.wav' },
  zent_hit2: { 'b1': 'ST-08/zent hit2.wav' },
  zent_hm_yum: { 'b1': 'ST-08/zent hm...yum.wav' },
  zent_hm: { 'b1': 'ST-08/zent hm.wav' },
  zent_hueg: { 'b1': 'ST-08/zent hueg.wav' },
  zent_huhn: { 'b1': 'ST-08/zent huhn.wav' },
  zent_huhn2: { 'b1': 'ST-08/zent huhn2.wav' },
  zent_huhn3: { 'b1': 'ST-08/zent huhn3.wav' },
  zent_hupp: { 'b1': 'ST-08/zent hupp.wav' },
  zent_knirsch: { 'b1': 'ST-08/zent knirsch.wav' },
  zent_knirsch2: { 'b1': 'ST-08/zent knirsch2.wav' },
  zent_kopfpling: { 'b1': 'ST-08/zent kopfpling.wav' },
  zent_krebs: { 'b1': 'ST-08/zent krebs.wav' },
  zent_lawa: { 'b1': 'ST-08/zent lawa.wav' },
  zent_lion: { 'b1': 'ST-08/zent lion.wav' },
  zent_lion2: { 'b1': 'ST-08/zent lion2.wav' },
  zent_monsterda: { 'b1': 'ST-08/zent monsterda.wav' },
  zent_monstertot: { 'b1': 'ST-08/zent monstertot.wav' },
  zent_motorsaege: { 'b1': 'ST-08/zent motorsaege.wav' },
  zent_oh: { 'b1': 'ST-08/zent oh.wav' },
  zent_ruelps: { 'b1': 'ST-08/zent ruelps.wav' },
  zent_saying: { 'b1': 'ST-08/zent saying .wav' },
  zent_saying2: { 'b1': 'ST-08/zent saying2.wav' },
  zent_saying3: { 'b1': 'ST-08/zent saying3.wav' },
  zent_saying4: { 'b1': 'ST-08/zent saying4.wav' },
  zent_schlug: { 'b1': 'ST-08/zent schlug.wav' },
  zent_scratch: { 'b1': 'ST-08/zent scratch.wav' },
  zent_sdrum: { 'b1': 'ST-08/zent sdrum .wav' },
  zent_shuff: { 'b1': 'ST-08/zent shuff.wav' },
  zent_shuff2: { 'b1': 'ST-08/zent shuff2.wav' },
  zent_snake: { 'b1': 'ST-08/zent snake.wav' },
  zent_snake2: { 'b1': 'ST-08/zent snake2.wav' },
  zent_ton: { 'b1': 'ST-08/zent ton.wav' },
  zent_ton2: { 'b1': 'ST-08/zent ton2.wav' },
  zent_ton3: { 'b1': 'ST-08/zent ton3.wav' },
  zent_tropfen: { 'b1': 'ST-08/zent tropfen.wav' },
  zent_ugh: { 'b1': 'ST-08/zent ugh.wav' },
  zent_urgh: { 'b1': 'ST-08/zent urgh .wav' },
  zent_wahahaha: { 'b1': 'ST-08/zent wahahaha.wav' },
  zent_wihihihi: { 'b1': 'ST-08/zent wihihihi.wav' },
  zent_wind: { 'b1': 'ST-08/zent wind.wav' },
  zent_yum: { 'b1': 'ST-08/zent yum.wav' }
}, 'github:fongelias/ias/main/converted')