samples({
  acoguit: { 'b1': 'ST-05/acoguit.wav' },
  base1: { 'b1': 'ST-05/base1.wav' },
  bassdrum23: { 'b1': 'ST-05/bassdrum23.wav' },
  bassdrum24: { 'b1': 'ST-05/bassdrum24.wav' },
  bassdrum25: { 'b1': 'ST-05/bassdrum25.wav' },
  bigsnare: { 'b1': 'ST-05/bigsnare.wav' },
  bigsnare1: { 'b1': 'ST-05/bigsnare1.wav' },
  bigsnare2: { 'b1': 'ST-05/bigsnare2.wav' },
  bomm: { 'b1': 'ST-05/bomm.wav' },
  brum: { 'b1': 'ST-05/brum.wav' },
  bum1: { 'b1': 'ST-05/bum1.wav' },
  bumper: { 'b1': 'ST-05/bumper.wav' },
  cc3_4: { 'b1': 'ST-05/cc3+4.wav' },
  cc4: { 'b1': 'ST-05/cc4.wav' },
  chinagong: { 'b1': 'ST-05/chinagong.wav' },
  dingding: { 'b1': 'ST-05/dingding.wav' },
  drake1: { 'b1': 'ST-05/drake1.wav' },
  drip: { 'b1': 'ST-05/drip.wav' },
  droehn: { 'b1': 'ST-05/droehn.wav' },
  dum: { 'b1': 'ST-05/dum.wav' },
  edrum1: { 'b1': 'ST-05/edrum1.wav' },
  elec_guitare: { 'b1': 'ST-05/elec-guitare.wav' },
  elec_guitare4: { 'b1': 'ST-05/elec-guitare4.wav' },
  endblaster: { 'b1': 'ST-05/endblaster.wav' },
  eug: { 'b1': 'ST-05/eug.wav' },
  floete: { 'b1': 'ST-05/floete.wav' },
  floete2: { 'b1': 'ST-05/floete2.wav' },
  floete3: { 'b1': 'ST-05/floete3.wav' },
  floete4: { 'b1': 'ST-05/floete4.wav' },
  floete5: { 'b1': 'ST-05/floete5.wav' },
  fugger2: { 'b1': 'ST-05/fugger2.wav' },
  funktjunk: { 'b1': 'ST-05/funktjunk.wav' },
  gameover: { 'b1': 'ST-05/gameover.wav' },
  getready: { 'b1': 'ST-05/getready.wav' },
  groll: { 'b1': 'ST-05/groll.wav' },
  guitardown: { 'b1': 'ST-05/guitardown.wav' },
  heldguitar: { 'b1': 'ST-05/heldguitar.wav' },
  highhat8: { 'b1': 'ST-05/highhat8.wav' },
  hihat6: { 'b1': 'ST-05/hihat6.wav' },
  hohlbasdrum: { 'b1': 'ST-05/hohlbasdrum.wav' },
  hohlsnaredrum: { 'b1': 'ST-05/hohlsnaredrum.wav' },
  impossible4: { 'b1': 'ST-05/impossible4.wav' },
  jamigo_low_sdrum: { 'b1': 'ST-05/jamigo low sdrum.wav' },
  jamigosdrum: { 'b1': 'ST-05/jamigosdrum.wav' },
  laser: { 'b1': 'ST-05/laser.wav' },
  laugh: { 'b1': 'ST-05/laugh.wav' },
  mark2: { 'b1': 'ST-05/mark2.wav' },
  monstergong: { 'b1': 'ST-05/monstergong.wav' },
  motor: { 'b1': 'ST-05/motor.wav' },
  nonstop: { 'b1': 'ST-05/nonstop.wav' },
  ohhh1: { 'b1': 'ST-05/ohhh1.wav' },
  operator: { 'b1': 'ST-05/operator.wav' },
  pock: { 'b1': 'ST-05/pock.wav' },
  pock4: { 'b1': 'ST-05/pock4.wav' },
  ptschiu: { 'b1': 'ST-05/ptschiu.wav' },
  rguitar1: { 'b1': 'ST-05/rguitar1.wav' },
  rpiano: { 'b1': 'ST-05/rpiano.wav' },
  secret_sound: { 'b1': 'ST-05/secret sound.wav' },
  short: { 'b1': 'ST-05/short.wav' },
  shot3: { 'b1': 'ST-05/shot3.wav' },
  snare12: { 'b1': 'ST-05/snare12.wav' },
  snare15: { 'b1': 'ST-05/snare15.wav' },
  snare21: { 'b1': 'ST-05/snare21.wav' },
  snaredrum: { 'b1': 'ST-05/snaredrum.wav' },
  snaredrum70: { 'b1': 'ST-05/snaredrum70.wav' },
  snaredrum8: { 'b1': 'ST-05/snaredrum8.wav' },
  speech3: { 'b1': 'ST-05/speech3.wav' },
  starsnare: { 'b1': 'ST-05/starsnare.wav' },
  synth4: { 'b1': 'ST-05/synth4.wav' },
  synth5: { 'b1': 'ST-05/synth5.wav' },
  synth6: { 'b1': 'ST-05/synth6.wav' },
  synth9: { 'b1': 'ST-05/synth9.wav' },
  synthgong: { 'b1': 'ST-05/synthgong.wav' },
  technobass2: { 'b1': 'ST-05/technobass2.wav' },
  tom1: { 'b1': 'ST-05/tom1.wav' },
  tomdrum: { 'b1': 'ST-05/tomdrum.wav' },
  tomdrum2: { 'b1': 'ST-05/tomdrum2.wav' },
  tomtom4: { 'b1': 'ST-05/tomtom4.wav' },
  tsong2: { 'b1': 'ST-05/tsong2.wav' },
  uaaa2: { 'b1': 'ST-05/uaaa2.wav' },
  umpf: { 'b1': 'ST-05/umpf.wav' },
  uuh: { 'b1': 'ST-05/uuh.wav' },
  vclaps2: { 'b1': 'ST-05/vclaps2.wav' },
  victoryguitar: { 'b1': 'ST-05/victoryguitar.wav' },
  vixenbass: { 'b1': 'ST-05/vixenbass.wav' },
  vixenbassdrum: { 'b1': 'ST-05/vixenbassdrum.wav' },
  vixenbongo: { 'b1': 'ST-05/vixenbongo.wav' },
  vixensnare: { 'b1': 'ST-05/vixensnare.wav' },
  vixensnare2: { 'b1': 'ST-05/vixensnare2.wav' },
  vwood: { 'b1': 'ST-05/vwood.wav' },
  warrior3: { 'b1': 'ST-05/warrior3.wav' },
  wind: { 'b1': 'ST-05/wind.wav' },
  zent_camera: { 'b1': 'ST-05/zent camera.wav' },
  zent_effekt: { 'b1': 'ST-05/zent effekt.wav' },
  zent_effekt3: { 'b1': 'ST-05/zent effekt3.wav' },
  zent_effekt4: { 'b1': 'ST-05/zent effekt4.wav' },
  zent_effekt5: { 'b1': 'ST-05/zent effekt5.wav' },
  zent_laser: { 'b1': 'ST-05/zent laser.wav' },
  zupp: { 'b1': 'ST-05/zupp.wav' }
}, 'github:fongelias/ias/main/converted')