samples({
  alle_batteri: { 'b1': 'ST-14/alle_batteri....wav' },
  jetanfang: { 'b1': 'ST-14/jetanfang.wav' },
  low_sword: { 'b1': 'ST-14/low-sword.wav' },
  onetwo: { 'b1': 'ST-14/onetwo.wav' },
  pianodur: { 'b1': 'ST-14/pianodur.wav' },
  pianomoll: { 'b1': 'ST-14/pianomoll.wav' },
  ruelps: { 'b1': 'ST-14/ruelps.wav' },
  setbass: { 'b1': 'ST-14/setbass.wav' },
  setbdrum: { 'b1': 'ST-14/setbdrum.wav' },
  setbit: { 'b1': 'ST-14/setbit.wav' },
  setbit2: { 'b1': 'ST-14/setbit2.wav' },
  setexplod: { 'b1': 'ST-14/setexplod.wav' },
  sethhat: { 'b1': 'ST-14/sethhat.wav' },
  setlaser: { 'b1': 'ST-14/setlaser.wav' },
  setlaser2: { 'b1': 'ST-14/setlaser2.wav' },
  setlaser3: { 'b1': 'ST-14/setlaser3.wav' },
  setsdrum: { 'b1': 'ST-14/setsdrum.wav' },
  setshaker: { 'b1': 'ST-14/setshaker.wav' },
  setvoice1: { 'b1': 'ST-14/setvoice1.wav' },
  snaredrumsample: { 'b1': 'ST-14/snaredrumsample.wav' },
  st2: { 'b1': 'ST-14/st2.wav' },
  super_distort: { 'b1': 'ST-14/super-distort.wav' },
  trinity: { 'b1': 'ST-14/trinity.wav' },
  willi1: { 'b1': 'ST-14/willi1.wav' },
  willi10: { 'b1': 'ST-14/willi10.wav' },
  willi2: { 'b1': 'ST-14/willi2.wav' },
  willi8: { 'b1': 'ST-14/willi8.wav' },
  zak_ahh: { 'b1': 'ST-14/zak ahh.wav' },
  zak_ahh2: { 'b1': 'ST-14/zak ahh2.wav' },
  zak_all: { 'b1': 'ST-14/zak all.wav' },
  zak_blast: { 'b1': 'ST-14/zak blast.wav' },
  zak_branch2: { 'b1': 'ST-14/zak branch2.wav' },
  zak_clink: { 'b1': 'ST-14/zak clink.wav' },
  zak_dofff: { 'b1': 'ST-14/zak dofff .wav' },
  zak_dofff2: { 'b1': 'ST-14/zak dofff...wav' },
  zak_door1: { 'b1': 'ST-14/zak door1.wav' },
  zak_door2: { 'b1': 'ST-14/zak door2.wav' },
  zak_doorclose: { 'b1': 'ST-14/zak doorclose.wav' },
  zak_drawer: { 'b1': 'ST-14/zak drawer.wav' },
  zak_dumpf_noise: { 'b1': 'ST-14/zak dumpf noise.wav' },
  zak_dumpf2: { 'b1': 'ST-14/zak dumpf2.wav' },
  zak_ei: { 'b1': 'ST-14/zak ei.wav' },
  zak_esq1: { 'b1': 'ST-14/zak esq1.wav' },
  zak_esq2: { 'b1': 'ST-14/zak esq2.wav' },
  zak_gong: { 'b1': 'ST-14/zak gong.wav' },
  zak_guitare: { 'b1': 'ST-14/zak guitare.wav' },
  zak_insidejet: { 'b1': 'ST-14/zak insidejet.wav' },
  zak_kazoo: { 'b1': 'ST-14/zak kazoo.wav' },
  zak_klingel: { 'b1': 'ST-14/zak klingel.wav' },
  zak_klo: { 'b1': 'ST-14/zak klo.wav' },
  zak_klong_1: { 'b1': 'ST-14/zak klong.(1)..wav' },
  zak_klong: { 'b1': 'ST-14/zak klong.wav' },
  zak_klong2: { 'b1': 'ST-14/zak klong2.wav' },
  zak_klopfen: { 'b1': 'ST-14/zak klopfen.wav' },
  zak_kueschrank: { 'b1': 'ST-14/zak kueschrank.wav' },
  zak_m_bass: { 'b1': 'ST-14/zak m-bass.wav' },
  zak_m_bdrum: { 'b1': 'ST-14/zak m-bdrum.wav' },
  zak_m_sdrum: { 'b1': 'ST-14/zak m-sdrum.wav' },
  zak_m_voice: { 'b1': 'ST-14/zak m-voice.wav' },
  zak_m_voice2: { 'b1': 'ST-14/zak m-voice2.wav' },
  zak_m2_bass: { 'b1': 'ST-14/zak m2-bass.wav' },
  zak_m2_bdrum: { 'b1': 'ST-14/zak m2-bdrum.wav' },
  zak_m2_sdrum: { 'b1': 'ST-14/zak m2-sdrum.wav' },
  zak_machine: { 'b1': 'ST-14/zak machine.wav' },
  zak_piano: { 'b1': 'ST-14/zak piano.wav' },
  zak_power: { 'b1': 'ST-14/zak power.wav' },
  zak_quesch: { 'b1': 'ST-14/zak quesch.wav' },
  zak_quesch2: { 'b1': 'ST-14/zak quesch2.wav' },
  zak_quesch3: { 'b1': 'ST-14/zak quesch3.wav' },
  zak_quesch4: { 'b1': 'ST-14/zak quesch4.wav' },
  zak_quesch5: { 'b1': 'ST-14/zak quesch5.wav' },
  zak_quil: { 'b1': 'ST-14/zak quil.wav' },
  zak_rolo: { 'b1': 'ST-14/zak rolo.wav' },
  zak_rolo2: { 'b1': 'ST-14/zak rolo2.wav' },
  zak_rumms: { 'b1': 'ST-14/zak rumms.wav' },
  zak_rumms2: { 'b1': 'ST-14/zak rumms2.wav' },
  zak_schnarchen: { 'b1': 'ST-14/zak schnarchen.wav' },
  zak_tack: { 'b1': 'ST-14/zak tack.wav' },
  zak_tack2: { 'b1': 'ST-14/zak tack2.wav' },
  zak_tack3: { 'b1': 'ST-14/zak tack3.wav' },
  zak_tackin: { 'b1': 'ST-14/zak tackin.wav' },
  zak_tackout: { 'b1': 'ST-14/zak tackout.wav' },
  zak_tock1: { 'b1': 'ST-14/zak tock1.wav' },
  zak_transport: { 'b1': 'ST-14/zak transport.wav' },
  zak_uughh: { 'b1': 'ST-14/zak uughh.wav' },
  zak_voegel: { 'b1': 'ST-14/zak voegel.wav' },
  zak_voegel2: { 'b1': 'ST-14/zak voegel2.wav' },
  zak_voegel3: { 'b1': 'ST-14/zak voegel3.wav' },
  zak_voegel4: { 'b1': 'ST-14/zak voegel4.wav' },
  zak_voice: { 'b1': 'ST-14/zak voice.wav' },
  zak_water: { 'b1': 'ST-14/zak water.wav' },
  zak_water2: { 'b1': 'ST-14/zak water2.wav' },
  zak_wind: { 'b1': 'ST-14/zak wind.wav' },
  zak_windpfiff: { 'b1': 'ST-14/zak windpfiff.wav' },
  zak_windpfiff2: { 'b1': 'ST-14/zak windpfiff2.wav' },
  zent_adolf_a1: { 'b1': 'ST-14/zent adolf-a1.wav' },
  zent_adolf_a2: { 'b1': 'ST-14/zent adolf-a2.wav' },
  zent_adolf_a3: { 'b1': 'ST-14/zent adolf-a3.wav' },
  zent_adolf_a4: { 'b1': 'ST-14/zent adolf-a4.wav' },
  zent_adolf_a5: { 'b1': 'ST-14/zent adolf-a5.wav' },
  zent_adolf_a6: { 'b1': 'ST-14/zent adolf-a6.wav' },
  zent_adolf_a7: { 'b1': 'ST-14/zent adolf-a7.wav' },
  zent_adolf_a8: { 'b1': 'ST-14/zent adolf-a8.wav' },
  zent_adolf_ahh: { 'b1': 'ST-14/zent adolf-ahh.wav' },
  zent_adolf_ahh2: { 'b1': 'ST-14/zent adolf-ahh2.wav' },
  zent_adolf_hit1: { 'b1': 'ST-14/zent adolf-hit1.wav' },
  zent_adolf_hit2: { 'b1': 'ST-14/zent adolf-hit2.wav' },
  zent_adolf_hueh: { 'b1': 'ST-14/zent adolf-hueh.wav' },
  zent_b_dumpf: { 'b1': 'ST-14/zent b-dumpf.wav' },
  zent_b_her: { 'b1': 'ST-14/zent b-her.wav' },
  zent_b_hin: { 'b1': 'ST-14/zent b-hin.wav' },
  zent_b_kehrt: { 'b1': 'ST-14/zent b-kehrt.wav' },
  zent_b_trumpet: { 'b1': 'ST-14/zent b-trumpet.wav' },
  zent_c_monster1: { 'b1': 'ST-14/zent c-monster1.wav' },
  zent_c_monster2: { 'b1': 'ST-14/zent c-monster2.wav' },
  zent_maria_ahh: { 'b1': 'ST-14/zent maria-ahh.wav' },
  zent_maria_ahh2: { 'b1': 'ST-14/zent maria-ahh2.wav' },
  zent_maria_hueh: { 'b1': 'ST-14/zent maria-hueh.wav' },
  zent_zerfleisch: { 'b1': 'ST-14/zent zerfleisch.wav' }
}, 'github:fongelias/ias/main/converted')